apiVersion: v1
data:
  mongo_initdb_database: free5gc
kind: ConfigMap
metadata:
  name: f5gc-mongodb-config
  namespace: f5gc
---
apiVersion: v1
data: null
kind: ConfigMap
metadata:
  name: f5gc-mongodb-data
  namespace: f5gc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-mongodb
  name: f5gc-mongodb
  namespace: f5gc
spec:
  ports:
  - name: f5gc-mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: f5gc-mongodb
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: f5gc-mongodb
  namespace: f5gc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-mongodb
  serviceName: f5gc-mongodb
  template:
    metadata:
      labels:
        app: f5gc-mongodb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: mongo_initdb_database
              name: f5gc-mongodb-config
        image: mongo:4.2.7
        imagePullPolicy: IfNotPresent
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
      securityContext:
        runAsGroup: 0
        runAsUser: 0
